version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/starspin
    depends_on:
      - db
    networks:
      - starspin-network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starspin
    ports:
      - "5432:5432"
    networks:
      - starspin-network

volumes:
  postgres_data:

networks:
  starspin-network:
    driver: bridge 